### ISSUE TITLE
Image hosting guidelines

### ISSUE THREAD

**Issue by gustavosobral** [exercism/interactive-cli-walkthrough#18]
Me and @lhoBas noticed that the walkthrough images/screenshots are hosted mainly on Imgur.
I believe this is can be very tricky if the image URL changes and also for other contributors to put their own images on the project. 

It would not be better to host this images inside the repository itself? Or should we define a guideline to always upload images in a specific image hosting service?

**Comment by iHiD** [comment]
Hello @gustavosobral and @ihobas. Great points - thanks. 

We'll put them all onto s3. @ccare and @kntsoriano - could you think about how we manage this in line with OSS pls?

**Comment by rpottsoh** [comment]
I may attempt to write up a Windows 7 walk through....  I have no idea how to use the current system that is hosting the images.....  Can I add an `img` directory to the repo?

**Comment by kntsoriano** [comment]
Hi, everyone. I've merged https://github.com/exercism/interactive-cli-walkthrough/pull/39 in order to fix this problem. Thank you for opening this issue :)
