### ISSUE TITLE
Windows: Not starting at top of subsequent pages

### ISSUE THREAD

**Issue by rpottsoh** [exercism/interactive-cli-walkthrough#24]
During the Windows 10 walk through the user is asked a `yes` / `no` question at the bottom of the page.  Upon clicking the appropriate response I am not taken to the top of the new page but remain at the bottom of the new page.  In some instances it almost appears as though nothing has happened when the link is clicked because the new page also ends with a `yes` / `no` question to be answered.  This was confusing at first until I realized I needed to scroll to the top of the page to read what the new page was displaying... 

I am using Chrome on Windows 7 to realize the behavior I am reporting on.
![rpottsohwindows10_yesno](https://user-images.githubusercontent.com/6978003/40125219-6a0cf5bc-58f8-11e8-92f5-1941596a417b.gif)

**Comment by iHiD** [comment]
Thanks. Yeah, the walkthrough hasn't yet been visually designed or properly
integrated. It's coming soon though :)

**Comment by rpottsoh** [comment]
>  hasn't yet been visually designed or properly integrated

Good to know, thanks.  Feel free to close this issue if you think it is no longer relevant.
