### ISSUE TITLE
Windows versions to support?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/interactive-cli-walkthrough#26]
So far a start has been made that is exclusive to Windows 10 users.  Do we need or want walk through's for earlier versions of Windows?  I  haven't decided yet, but I may try my hand at a Windows 7 walk through.  I don't have access to Windows 8.

**Comment by kytrinyx** [comment]
I would like to do only Windows 10, as I *think* this is now the most common.

We have a line in there about other versions, and to contact the volunteers, which will give us more information about whether or not we need to add other instructions.

**Comment by kytrinyx** [comment]
> Would it be a good idea to have the walk through, optionally,route the user to the Installer if they were not successful in the manual installation.

That would be a brilliant idea. A separate path for "I don't have Windows 10" but before "talk to a volunteer" to use the installer would be a huge win, I think!

**Comment by rpottsoh** [comment]
Sounds good @kytrinyx.  I'll spend some time on this.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this as solved.
