### ISSUE TITLE
How does this get into the website?

### ISSUE THREAD

**Issue by iHiD** [exercism/interactive-cli-walkthrough#3]
The html doesn’t get into `prototype`, yet. We could do:
1) git subtree 
2) Periodic PRs
3) Make it behave the same way as `website-copy`.

**Comment by kytrinyx** [comment]
My plan was to use `git subtree` until we have the basic walkthrough all worked out.

Then merge it into website copy permanently and get rid of the separate repo.

The walkthrough is included in the website-copy repository as a git subtree. To bring in updates into the website-copy repo, run the command:

```
git subtree pull --prefix=walkthrough walkthrough master
```

This will include the full walkthrough contribution history in the website-copy repository. When we've finished developing the walkthrough we can archive the interactive-cli-walkthrough repository and do maintenance directly within the website-copy repository, and everyone still gets credit for their code.

**Comment by kntsoriano** [comment]
I think we can close this now as we've already decided on how the walkthrough gets into the website :)

As a sidenote, in order for the command @kytrinyx described above to work, I also needed to run this command:

```
git remote add walkthrough git@github.com:exercism/interactive-cli-walkthrough.git
```
