### ISSUE TITLE
Bash command mistaken for story passage

### ISSUE THREAD

**Issue by kytrinyx** [exercism/interactive-cli-walkthrough#31]
In the linux instructions there is a bash command that gets interpolated as a story passage:

https://github.com/exercism/interactive-cli-walkthrough/blob/52127e39b2f05b9c23b355b07157ac613912a125/linux/path.tw2#L13

The compiled output looks like this:

<img width="928" alt="compiled output" src="https://user-images.githubusercontent.com/276834/40579713-c9492b26-60e2-11e8-9a6e-e2f354148775.png">

Shall we rewrite the bash? Or is there a way of escaping this in twee2 so that it doesn't try to run javascript here?

@kntsoriano any ideas on this one? I'm not very familiar with twee2.

**Comment by kntsoriano** [comment]
@kytrinyx Currently, there is no way to escape in twee2, or to be more specific, there is no way to escape with the twee2 format we use.

In order to support escaping, we might need to fork the formatter we use right now and write it ourselves.

I think a quick fix for this would be to use single brackets for now. I'm just not sure what implications it has for bash.

**Comment by kytrinyx** [comment]
Yeah, I think the right way to go is to simplify or change the bash. Cool, I'll take a stab at it.

**Comment by iHiD** [comment]
@kytrinyx I've marked this as `status/pr-welcome` as I know you're limited on time. If you (or anyone else) start working on this, please remove that label :)

**Comment by kytrinyx** [comment]
Currently only maintainers can add/remove labels, but if you want to grab this one, please leave a comment and we'll remove the label for you 💙

**Comment by kntsoriano** [comment]
I'll start work on this. It's the same issue as https://github.com/exercism/exercism.io/issues/3862.

**Comment by iHiD** [comment]
@kntsoriano Can this be closed?

**Comment by kntsoriano** [comment]
Yes.
