### ISSUE TITLE
Windows Installer should be offered as an option earlier in the Windows 10 path

### ISSUE THREAD

**Issue by rpottsoh** [exercism/interactive-cli-walkthrough#47]
@kytrinyx  or @iHiD when traversing the Windows 10 path of the walk through the Windows Installer is offered as a way to install the CLI only after the student has failed at installing the CLI manually.  The student may only be interested in getting up and running as simply as possible.  I would like to propose that the student be presented with the choice of using the installer or following the manual process.  If they fail at the manual process they would still be offered the installer, as they are currently.

I am bringing this up as it appears the only way the student can learn about the CLI or downloading it is via. the walk through link that appears when an unlocked exercise is selected for the first time.

As a maintainer it would be nice to be able to see the site from time to time as a new student sees it; to make sure changes to documentation or links appear and work correctly.  This is a feature of v1 that I am missing.

**Comment by iHiD** [comment]
>  I would like to propose that the student be presented with the choice of using the installer or following the manual process. If they fail at the manual process they would still be offered the installer, as they are currently.

I think that's sensible. Are you ok to PR it?

> I am bringing this up as it appears the only way the student can learn about the CLI or downloading it is via. the walk through link that appears when an unlocked exercise is selected for the first time.

We're also going to bring instructions further out onto the locked track page I think.

> As a maintainer it would be nice to be able to see the site from time to time as a new student sees it; to make sure changes to documentation or links appear and work correctly. This is a feature of v1 that I am missing.

Can you expand on where that's not the case please?

**Comment by rpottsoh** [comment]
> Can you expand on where that's not the case please?

I don't see how I can visit the Delphi track page and see it just as someone would just starting an exercise, clicking it for the first time after it was unlocked.  

For example, I only see a way to get here, https://exercism.io/tracks/delphi/installation, because pangram is now unlocked for me and the intro page for the exercise is still available to me since I have not yet submitted a solution.  Once I submit a solution a lot of this information is hidden away.

I believe there is an issue related to this somewhere, I don't know where though.  Under v1 all of the documentation that a track had available was always easy to find.  At the moment the stricter feeling of the v2 structure only allows me to see what someone thinks I only need to see.  This is too restrictive.  We need to be able climb to a higher altitude from time to time to see other aspects that previous choices have locked us out of.  Does that make sense?

re: a PR.  I should be able to, though I have lost my ability to compile so cannot test.  Updating the tw2 files is usually not too big of a deal.

**Comment by iHiD** [comment]
That makes sense. We'll look into it. My suggestion in the interim would be
to sign up as a new user and explore that way.

**Comment by rpottsoh** [comment]
> sign up as a new user and explore that way.

The thought had crossed my mind, but creating dummy users while effective is kludgy.  

:bulb:  if using dummy users is an easier way to handle this wouldn't it be nice to, perhaps, omit these dummy users from statistical information?  Perhaps if there was some way to tag a maintainers' dummy doppelganger so that it would be "ignored" essentially.....  I wouldn't want excessive use of a dummy account to influence the numbers...

**Comment by rpottsoh** [comment]
> For the question about how to support maintainers in navigating a track as a new user, would you please open an issue in exercism/exercism.io?

Will do, this evening hopefully.
