### ISSUE TITLE
Prefix 32 and 64 architectures with x86 to distinguish from ARM

### ISSUE THREAD

**Issue by vbuell** [exercism/interactive-cli-walkthrough#58]
The sentence "32-bit vs 64-bit vs ARM" is confusing since ARM has 64 extension as well. Would be cleaner if it is replaced with something like "x86 (32-bit) vs x86_64 vs ARM". The same issue with the naming of released tarballs - the name should contain full qualified architecture name, not just a width of the cpu registers.

**Comment by kytrinyx** [comment]
@vbuell I didn't realize ARM had 64 bit. In light of this, I think it would make sense to change it per your suggestion.

I'll open an issue regarding the release tarballs.

**Comment by iHiD** [comment]
@vbuell Could you take a look at https://github.com/exercism/interactive-cli-walkthrough/pull/80 pls :)
