### ISSUE TITLE
Add installation instructions for Linux

### ISSUE THREAD

**Issue by kntsoriano** [exercism/interactive-cli-walkthrough#6]
## Background
In order to help Linux users to get started on exercism, a walkthrough to install the CLI must be written for them.

## Linux-specific walkthrough

In v1 we have instructions for a manual installation. They're short and sweet and assume that as a Linux user you are probably comfortable on the command-line: http://exercism.io/clients/cli/linux

This can probably be converted to one or two simple steps. We don't need a detailed walkthrough for beginners on Linux at this time—if we need it later, we can likely convert a lot of the detailed stuff from the mac walkthrough.

Don't worry too much about getting the copy/wording right—just getting the decision tree in place will make it much easier for others to take a stab at improving things.

## Contributing guide
In order to get you up to speed, we have prepared a [Contributing Guide](https://github.com/exercism/interactive-cli-walkthrough/blob/master/CONTRIBUTING.md).

**Comment by kytrinyx** [comment]
We got some feedback about linux installation instructions on the v1 site here: https://github.com/exercism/exercism.io/issues/3764

It would be great if someone has time to go through the current linux flow to check if there are improvements to be made based on that feedback.

**Comment by kytrinyx** [comment]
I'm going to call this "done". We will likely get improvements and polish as people start using it.
