### ISSUE TITLE
HTML fragments rendered in code block

### ISSUE THREAD

**Issue by NobbZ** [exercism/interactive-cli-walkthrough#66]
In https://github.com/exercism/interactive-cli-walkthrough/blob/master/contents/linux/path.tw2 there is a codeblock with the following content:

````
```
[[ ":$PATH:" == *":$HOME/bin:"* || ":$PATH:" == *":~/bin:"* ]] && echo "~/bin is in PATH" || echo "~/bin is not in PATH"
```
````

It is rendered on the page as

> ```
> <a href="javascript:void(0)" data-passage="| &quot;:$PATH:&quot; == *&quot;:~/bin:&quot;* "> ":$PATH:" == *":$HOME/bin:"* </a> && echo "~/bin is in PATH" || echo "~/bin is not in PATH"
> ```

**Comment by NobbZ** [comment]
I've checked again today and it seems to be fixed. Is this related to cosmic radiation or has an actual fix happened?

**Comment by iHiD** [comment]
Maybe https://github.com/exercism/interactive-cli-walkthrough/pull/67 ?

**Comment by NobbZ** [comment]
Yes, from the description from the PR it would fit.

**Comment by kntsoriano** [comment]
You both are correct that #67 fixes this issue. Thanks for reminding me that I've left this issue open. I'll close it for now :)
