### ISSUE TITLE
Add installation instructions for Windows

### ISSUE THREAD

**Issue by kntsoriano** [exercism/interactive-cli-walkthrough#7]
## Background
In order to help Windows users to get started on exercism, a walkthrough to install the CLI must be written for them.

## Prior Art
The v1 site has [instructions for installing on Windows](http://exercism.io/clients/cli/windows) using an installer and using a package manager (Chocolatey). We also have instructions for manually downloading the binary and putting it in your path (http://exercism.io/clients/cli/install#installing-manually).

## Expert vs Beginner

We need two paths through for each language:
1. for those who already are comfortable with all the steps. Walking through detailed instructions is incredibly frustrating when all you need is the package name or where to download the binary.
1. for those who are unfamiliar and probably feeling intimidated by the whole process. They'll need a lot more detail and reassurance.

In the future we may expand this to have three paths through:

1. Quick, no explanation
1. Detailed steps, no handholding
1. At each detailed step, the option to get more detail/screenshots/visual guide etc

## Windows-specific walkthrough
We are no longer going to explain how to use Chocolatey,. We can include one step that says how to install with the package manager _if you already have it installed_ (e.g. it should just be one instruction long).

Once you select Windows, the choices should be as follows:

* Install with Chocolatey
* Install by downloading an installer
* Install manually

Don't worry _too_ much about the copy/wording on the first pass, getting the decision tree in place will make it much easier for other people to take a stab at improving the flow.

_Note: you don't need to commit to doing the whole thing. If you can help us get just a few steps documented, we'll have a much better starting point for others to contribute._

## Contributing guide
In order to get you up to speed, we have prepared a [Contributing Guide](https://github.com/exercism/interactive-cli-walkthrough/blob/master/CONTRIBUTING.md).

**Comment by rpottsoh** [comment]
I am trying to understand how this figures in with the [Installer for the Exercism Windows Command-Line Client](https://github.com/exercism/windows-installer#installer-for-the-exercism-windows-command-line-client).

**Comment by kytrinyx** [comment]
@rpottsoh Sorry it's taken so long to answer this. I'd like to get the manual installation flow worked out first, because I think we will always need to have that as a backup. Once we have this, let's go back to the installer so we can upgrade the instructions with a shortcut for people to try first.

**Comment by kytrinyx** [comment]
@rpottsoh I changed my mind :) I just looked through the README and instructions for the installer. I think we should make this the first path through, same as we have homebrew by default for Mac. Then, if someone doesn't want to use it, we guide them through the steps of installing manually via the download of the binary.

**Comment by lhoBas** [comment]
👋 I'll try to write a Windows howto to install v2 during RossConf. Seems doable on Windows 10, so I'll focus on that.

**Comment by kytrinyx** [comment]
@rpottsoh sensitive -- as in it will let you select which one you want?

**Comment by rpottsoh** [comment]
No.  It will sense when the release version is V3 instead of V2.  I am not at a computer to reference the discussion we had on this.  I'll  try to do that later.  For V3 the configuration step is omitted.


Sent from my android device.

**Comment by rpottsoh** [comment]
@kytrinyx I think exercism/windows-installer#26 lays things out pretty well and describes the current state of the Windows installer.  Let me know if you have questions or if you are interested in changing things up at all.

**Comment by kytrinyx** [comment]
I'm going to call this "done". We will likely get improvements and polish as people start using it.
